# Generated by Django 5.0.6 on 2024-05-23 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todos', '0003_answer_correctanswer_level_question_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variants', models.JSONField()),
            ],
        ),
        migrations.RemoveField(
            model_name='correctanswer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='question',
            name='level_id',
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_name', models.CharField(max_length=255)),
                ('level', models.CharField(choices=[('1', 'One'), ('2', 'Two'), ('3', 'Three'), ('4', 'Four'), ('5', 'Five'), ('6', 'Six'), ('7', 'Seven'), ('8', 'Eight'), ('9', 'Nine'), ('10', 'Ten')], max_length=100)),
                ('correct_answer', models.IntegerField()),
                ('variants_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Todos.variants')),
            ],
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='CorrectAnswer',
        ),
        migrations.DeleteModel(
            name='Level',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
