# Generated by Django 5.0.6 on 2024-05-23 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Todos', '0004_variants_remove_correctanswer_question_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Restaurant',
            new_name='Question',
        ),
    ]
